blog/urls.py
from django.conf.urls import url
from . import views

from django.contrib.auth.decorators import login_required

# regular expression >>> re(r) 正则表达式


#  告诉 Django 这个 urls.py 模块是属于 blog 应用的，这种技术叫做视图函数命名空间
app_name = 'blog'
urlpatterns = [
    #  调用类视图的 as_view() 方法,将类视图转换成函数视图
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$',login_required(views.PostDetailView.as_view()),name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesView.as_view(),name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$',views.TagView.as_view(),name='tag'),
    #url(r'^search/$',views.search,name='search'),
]

publish/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'publish'
urlpatterns = [
    url(r'^publish/$', login_required(views.publishs), name='publishs'),
    url(r'^change_post/(?P<pk>[0-9]+)/$',login_required(views.change_post),name='change_post'),
]

startproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/',include('haystack.urls')),
    url(r'^accounts/',include('users.urls')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^',include('blog.urls')),
    url(r'^',include('comment.urls')),
    url(r'^',include('publish.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
app_name = 'users'
urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^show/(?P<pk>[0-9]+)/$', login_required(views.show), name='usershow'),
    url(r'^change/(?P<pk>[0-9]+)/$', login_required(views.change), name='change'),
]

templates/base.html
{% extends 'up_base.html' %}
{% load blog_tags %}

{% block content %}
    <div class="container">
    <div class="row">

      {% block main %}

      {% endblock %}
        <aside class="col-md-4">
            {% block toc %}

            {% endblock %}
            <div class="widget widget-recent-posts">
                <h3 class="widget-title">最新文章</h3>
                {% get_recent_posts as recent_post_list %}
                <ul>
                    {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">
                                {{ post.title }}
                            </a>
                        </li>
                    {% empty %}
                        没有文章！
                    {% endfor %}
                </ul>
            </div>
            <div class="widget widget-archives">
                <h3 class="widget-title">归档</h3>
                {% archives as date_list %}
                <ul>
                    {% for data in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' data.year data.month %}">
                                {{ data.year }}年{{ data.month }}月
                            </a>
                        </li>
                    {% empty %}
                        没有归档！
                    {% endfor %}
                </ul>
            </div>

            <div class="widget widget-category">
                <h3 class="widget-title">分类</h3>
                {% get_categories as category_list %}
                <ul>
                    {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">
                                {{ category.name }}<span class="post-count">（{{ category.num_posts }}）</span>
                            </a>
                        </li>
                    {% empty %}
                        没有分类！
                    {% endfor %}
                </ul>
            </div>

            <div class="widget widget-tag-cloud">
                <h3 class="widget-title">标签云</h3>
                {% get_tags as tag_list %}
                <ul>
                    {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">
                                {{ tag.name }}<{{ tag.num_posts }}>
                            </a>
                        </li>
                    {% empty %}
                        暂无标签！
                    {% endfor %}
                </ul>
            </div>
            <div class="rss">
                <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
            </div>
        </aside>
    </div>
</div>
{% endblock %}

templates/up_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <title>于寂浪 &amp; yujilang</title>

    <style>
        span.highlighted {
            color: red;
        }
    </style>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    {% block static %}
    {% endblock %}
    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    {#  代码高亮  #}
    <link rel="stylesheet" href="{% static 'blog/css/highlights/borland.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>于寂浪</b> &amp; yujilang</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            {% if user.is_authenticated %}
                                {# 如果是超级用户登录， 则显示 发帖 选项 #}
                                {% if user.username == 'chen' %}
                                    <li class="cl-effect-11"><a href="{% url 'publish:publishs' %}" data-hover="发帖">发帖</a></li>
                                {% endif %}
                                <li class="cl-effect-11"><a href="{% url 'users:usershow' user.pk %}">欢迎您：{{ user.username }}</a></li>
                                {# 显示用户头像 #}
                                <li class="cl-effect-11"><a><img class="img-circle" style="margin-top: -10px" width="40" height="40" src="{{ request.user.profile.avatar.url }}" /></a></li>
                                {# request.path 是用户当前访问页面的 URL #}
                                <li class="cl=effect-ll"><a href="{% url 'password_change' %}">修改密码</a></li>
                                <li class="cl-effect-11"><a href="{% url 'logout' %}" >退出</a></li>
                            {% else %}
                                <li class="cl-effect-11"><a href="{% url 'login' %}?next={{ request.path }}">登陆</a></li>
                                <li class="cl-effect-11"><a href="{% url 'users:register' %}">注册</a></li>
                            {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name='q' placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
{% block content %}
{% endblock %}
</div>


<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>