blog/urls.py
from django.conf.urls import url
from . import views

from django.contrib.auth.decorators import login_required

# regular expression >>> re(r) 正则表达式


#  告诉 Django 这个 urls.py 模块是属于 blog 应用的，这种技术叫做视图函数命名空间
app_name = 'blog'
urlpatterns = [
    #  调用类视图的 as_view() 方法,将类视图转换成函数视图
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$',login_required(views.PostDetailView.as_view()),name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesView.as_view(),name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$',views.TagView.as_view(),name='tag'),
    #url(r'^search/$',views.search,name='search'),
]

publish/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'publish'
urlpatterns = [
    url(r'^publish/$', login_required(views.publishs), name='publishs'),
    url(r'^change_post/(?P<pk>[0-9]+)/$',login_required(views.change_post),name='change_post'),
]

startproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/',include('haystack.urls')),
    url(r'^accounts/',include('users.urls')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^',include('blog.urls')),
    url(r'^',include('comment.urls')),
    url(r'^',include('publish.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
app_name = 'users'
urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^show/(?P<pk>[0-9]+)/$', login_required(views.show), name='usershow'),
    url(r'^change/(?P<pk>[0-9]+)/$', login_required(views.change), name='change'),
]

users/models.py
from django.core.validators import RegexValidator
from django.db import models

from django.contrib.auth.models import User

#  第一种方法
class Profile(models.Model):
    #  给自定义的用户模型新增了一个 nickname（昵称）属性，
    #  用来记录用户的昵称信息
    nickname = models.CharField(max_length=64)
    #  电话 可以为空
    phone = models.CharField(max_length=11, null=True, blank=True,
                             error_messages={
                                 'phone_err': '号码格式有误',
                             },
                             validators=[
                                 RegexValidator(regex='1[3578][0-9]{9}', message='号码格式有误',
                                                code='phone_err')])
    #  头像 upload_to 头像保存地址 default 默认头像
    avatar = models.ImageField(upload_to='avatar',default="avatar/1.jpg")

    #  Profile 与 User 是一对一的关系
    user = models.OneToOneField(User)

#  第二种方法
#  这种方法只能用于第一次迁移数据库之前设置
# from django.contrib.auth.models import AbstractUser
#
# class User(AbstractUser):
#     nickname = models.CharField(max_length=64,blank=True)
#
#     class Meta(AbstractUser.Meta):
#         pass

# Create your models here.

users/forms.py
from  django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import Input

from .models import Profile
from django.forms import ModelForm
#  第一种方法
from django.contrib.auth.models import User

#  第二种方法
#from .models import User

#  用户信息显示表单
class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username','email']

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        #  设置表单显示字段
        fields = ['avatar']
        #  设置字段的标签名字
        labels = {'avatar':'头像'}

#  用户信息修改表单
class User1Form(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']
        widgets = {'username': Input(attrs={'class': "form-control"}),
                   'email': Input(attrs={'class': "form-control"})}

class User2Form(ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'phone' ,'avatar']
        labels = {'avatar': '用户头像',
                  'nickname':'昵称',
                  'phone':'手机号码'}
        widgets = {'nickname': Input(attrs={'class': "form-control"}),
                   'phone': Input(attrs={'class': "form-control"})}

users/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import Profile
from django.contrib.auth.models import User

#  带表单的视图函数的经典写法
def register(request):
    # 从 get 或者 post 请求中获取 next 参数值
    # get 请求中，next 通过 url 传递，即 /?next=value
    # post 请求中，next 通过表单传递，即 <input type="hidden" name="next" value = "{{ next }}" / >
    redirect_to = request.POST.get('next', request.GET.get('next', ''))

    #  只有当请求为 POST 时，才表示用户提交了注册信息
    if request.method == 'POST':

        #  request.POST 是一个类字典数据结构，记录了用户提交的注册信息
        #  这里提交的就是用户名（username）、密码（password）、邮箱（email）
        #  用这些数据实例化一个用户注册表单
        form = RegisterForm(request.POST)
        #  上传文件要加入 request.FILES 字段
        form1 = ProfileForm(request.POST, request.FILES)
        #  验证数据的合法性
        if form.is_valid():
            if form1.is_valid():
                #  如果提交数据合法，调用表单的 save 方法将用户数据保存到数据库（所谓的注册，就是把用户信息放在数据库中）
                user = form.save()
                profile = form1.save(commit=False)
                profile.user = user
                profile.save()

                #  注册成功，跳转回首页
                if redirect_to:
                    return redirect(redirect_to)
                else:
                    return redirect('login')
    else:
        #  请求不是 POST，表明用户正在访问注册页面，展示一个空的注册表单给用户
        form = RegisterForm()
        form1 = ProfileForm()

    #  渲染模板
    #  如果用户正在访问注册页面，则渲染的是一个空的注册表单

    #  如果用户通过表单提交注册信息，但是数据验证不合法，则渲染的是一个带有错误信息的表单
    # 将记录用户注册前页面的 redirect_to 传给模板，以维持 next 参数在整个注册流程中的传递
    return render(request, 'users/register.html', context={'form': form, 'profile':form1,'next':redirect_to})

#  用户信息显示视图函数
def show(request,pk):
    user_list = User.objects.get(id=int(pk))
    return render(request, 'users/show.html', locals())

#  用户信息修改视图函数
def change(request, pk):
    #   获取当前 id 对象的用户信息
    user = User.objects.get(id=pk)
    profile = Profile.objects.get(user=user)
    if request.method == 'POST':
        #   将用户所修改信息与获取信息相关联，指定给谁做修改
        user_form = User1Form(request.POST, instance=user)
        profile_form = User2Form(request.POST, request.FILES, instance=profile)
        if user_form.is_valid():
            if profile_form.is_valid():
                user_form.save()
                profile_form.save()
                return redirect('users:usershow',pk)
    else:
        #  将当前 id 信息返回给页面
        user_form = User1Form( instance=user)
        profile_form = User2Form( instance=profile)
    return render(request, 'users/change.html', locals())

templates/users/change.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
    <style>
        span.highlighted {
            color: red;
        }
    </style>
    <title>于寂浪 &amp; yujilang</title>
    <link href="{% static 'users/css/bootstrap.css' %}" rel='stylesheet' type='text/css'/>
    <link href="{% static 'users/css/style.css' %}" rel='stylesheet' type='text/css'/>
    <link href='//fonts.googleapis.com/css?family=Asap:400,700,400italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>
</head>
<body>

<div id="home" class="header">
    <div class="container">
        <!-- top-hedader -->
        <div class="top-header">
            <div class="top-nav">
                <div class="navigation">
                    <div class="logo">
                        <h1><a href="{% url 'blog:index' %}">yujilang</a></h1>
                    </div>
                    <div class="navigation-right">
                        <nav class="link-effect-3" id="link-effect-3">
                            <ul class="nav1 nav nav-wil">
                                <li class="scroll"><a href="{% url 'blog:index' %}">首页</a></li>
                                {% if user.is_authenticated %}
                                    {% if user.username == 'chen' %}
                                        <li><a class="scroll" href="{% url 'publish:publishs' %}">发帖</a>
                                        </li>
                                    {% endif %}
                                    <li><a class="scroll"
                                           href="{% url 'users:usershow' user.pk %}">{{ user.username }}</a></li>
                                    <li><a class="scroll"><img class="img-circle"
                                                               style="margin-top: -10px"
                                                               width="40" height="40"
                                                               src="{{ request.user.profile.avatar.url }}"/></a>
                                    </li>
                                    <li><a class="scroll" href="{% url 'password_change' %}">修改密码</a>
                                    </li>
                                    <li><a class="scroll" href="{% url 'logout' %}">退出</a></li>
                                {% else %}
                                    <li><a class="scroll" href="{% url 'login' %}">登陆</a></li>
                                    <li><a class="scroll" href="{% url 'users:register' %}">注销</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>

            <div class="banner-info">
                <form method="post" action="{% url 'users:change' user.id %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-md-7 header-right">
                        <h1>Hi !</h1>
                        <h6>All things in their being are good for something</h6>
                        <ul class="address">
                            {% for form in user_form %}
                                <li>
                                    <ul class="address-text">
                                        <li><b>{{ form.label_tag }}</b></li>
                                        {{ form }}
                                        {{ form.errors }}
                                    </ul>
                                </li>
                            {% endfor %}
                            <li>
                                <ul class="address-text">
                                    <li><b>{{ profile_form.nickname.label_tag }}</b></li>
                                    {{ profile_form.nickname }}
                                </ul>
                            </li>
                            <li>
                                <ul class="address-text">
                                    <li><b>{{ profile_form.phone.label_tag }}</b></li>
                                    {{ profile_form.phone }}
                                    {{ profile_form.phone.errors }}
                                </ul>
                            </li>
                            <li>
                                <ul class="address-text">
                                    <li><b>{{ profile_form.avatar.label_tag }}</b></li>
                                    <li>{{ profile_form.avatar }}</li>

                                </ul>
                            </li>
                        </ul>
                        <button style="margin-top: 50px" type="submit" class="btn btn-primary">确认</button>
                        <a href="{% url 'users:usershow' user.id %}">
                            <button style="margin-top: 50px" type="button" class="btn btn-info">返回</button>
                        </a>
                    </div>
                    <div class="col-md-5 header-left">
                        <img src="{{ user.profile.avatar.url }}">
                    </div>
                </form>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>注册</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h3>注册</h3>
                <form class="form" action="{% url 'users:register' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {# 实际上是label标签 #}
                        {{ field.label_tag }}
                        {# 实际上是input标签 #}
                        {{ field }}
                        {# 报错 #}
                        {{ field.errors }}
                        {# 如果有帮助信息，则显示 #}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    {{ profile.avatar.label_tag }}
                    {{ profile.avatar }}
                    {{ profile.avatar.errors }}
                    <button type="submit" class="btn btn-primary btn-block">注册</button>
                    <input type="hidden" name="next" value="{{ next }}"/>
                </form>
                <div class="flex-center top-gap text-small">
                    <a href="{% url 'login' %}">已有账号登录</a>
                </div>
                <div class="flex-center top-gap text-small">
                    <a href="{% url 'blog:index' %}">返回首页</a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/users/show.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
    <title>于寂浪 &amp; yujilang</title>
    <link href="{% static 'users/css/bootstrap.css' %}" rel='stylesheet' type='text/css'/>
    <link href="{% static 'users/css/style.css' %}" rel='stylesheet' type='text/css'/>
    <link href='//fonts.googleapis.com/css?family=Asap:400,700,400italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>
</head>
<body>

<div id="home" class="header">
    <div class="container">
        <!-- top-hedader -->
        <div class="top-header">
            <div class="top-nav">
                <div class="navigation">
                    <div class="logo">
                        <h1><a href="{% url 'blog:index' %}">yujilang</a></h1>
                    </div>
                    <div class="navigation-right">
                        <nav class="link-effect-3" id="link-effect-3">
                            <ul class="nav1 nav nav-wil">
                                <li class="scroll"><a href="{% url 'blog:index' %}">首页</a></li>
                                {% if user.is_authenticated %}
                                    {% if user.username == 'chen' %}
                                        <li><a class="scroll" href="{% url 'publish:publishs' %}">发帖</a>
                                        </li>
                                    {% endif %}
                                    <li><a class="scroll"
                                           href="{% url 'users:usershow' user.pk %}">{{ user.username }}</a></li>
                                    <li><a class="scroll"><img class="img-circle"
                                                                        style="margin-top: -10px"
                                                                        width="40" height="40"
                                                                        src="{{ request.user.profile.avatar.url }}"/></a>
                                    </li>
                                    <li><a class="scroll" href="{% url 'password_change' %}">修改密码</a>
                                    </li>
                                    <li><a class="scroll" href="{% url 'logout' %}">退出</a></li>
                                {% else %}
                                    <li><a class="scroll" href="{% url 'login' %}">登陆</a></li>
                                    <li><a class="scroll" href="{% url 'users:register' %}">注销</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>

            <div class="banner-info">
                <div class="col-md-7 header-right">
                    <h1>Hi !</h1>
                    <h6>All things in their being are good for something</h6>
                    <ul class="address">
                        <li>
                            <ul class="address-text">
                                <li><b>姓名</b></li>
                                <li>{{ user_list.username }}</li>
                            </ul>
                        </li>
                        <li>
                            <ul class="address-text">
                                <li><b>昵称</b></li>
                                <li>{{ user_list.profile.nickname }}</li>
                            </ul>
                        </li>
                        <li>
                            <ul class="address-text">
                                <li><b>电话</b></li>
                                {% if user_list.profile.phone %}
                                    <li>{{ user_list.profile.phone }}</li>
                                {% endif %}
                            </ul>
                        </li>
                        <li>
                            <ul class="address-text">
                                <li><b>Email</b></li>
                                <li>{{ user_list.email }}</li>
                            </ul>
                        </li>
                        {% if user_list.id == user.id %}
                            <li><a href="{% url 'users:change' user_list.id %}">
                                <button style="margin-top: 50px" type="button" class="btn btn-default">修改</button>
                            </a></li>
                        {% endif %}
                    </ul>
                </div>
                <div class="col-md-5 header-left">
                    <img src="{{ user_list.profile.avatar.url }}">
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

</body>
</html>